# Generated by Django 5.0.6 on 2024-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telusko_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.IntegerField(),
        ),
    ]
