# Generated by Django 5.0.6 on 2024-08-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recoverykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='RecoveryKey',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='key_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.keytype'),
        ),
        migrations.AlterField(
            model_name='keytype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.invoice'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
