# Generated by Django 5.0.6 on 2024-08-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invoice_key_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='key_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='KeyType',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
