# Generated by Django 5.0.6 on 2024-08-05 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_invoice_key_type_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='digital_keys/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryKeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('social_media_account', models.CharField(max_length=150)),
                ('last_used_password', models.CharField(blank=True, max_length=128, null=True)),
                ('id_card_upload', models.ImageField(upload_to='id_cards/')),
                ('contact_method', models.CharField(help_text='Enter a valid email or phone number.', max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
