# Generated by Django 5.0.6 on 2024-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_digitalkey_recoverykeyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bank_card', 'Bank Card'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('gift_card', 'Gift Card'), ('mobile_app', 'Mobile App Transfer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
