# Generated by Django 5.0.6 on 2024-08-11 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profileoption_socialmediaaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='profile_option',
        ),
        migrations.CreateModel(
            name='ProfileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('completed_transactions', models.PositiveIntegerField(default=0)),
                ('transaction_time_frame', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='social_apps/')),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_apps', to='accounts.profileapp')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileOption',
        ),
        migrations.DeleteModel(
            name='SocialMediaAccount',
        ),
    ]
