# Generated by Django 5.0.6 on 2024-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_socialmediaaccount_profile_option_profileapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='network_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='network_type',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin Network'), ('erc20', 'ERC-20 (Ethereum Network)'), ('trc20', 'TRC-20 (Tron Network)')], max_length=20, null=True),
        ),
    ]
