# Generated by Django 5.0.6 on 2024-08-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cryptowallet_network_cost_cryptowallet_network_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='network_cost',
            field=models.DecimalField(decimal_places=2, default=0.56, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='network_type',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin Network'), ('erc20', 'ERC-20 (Ethereum Network)'), ('trc20', 'TRC-20 (Tron Network)')], default=0, max_length=20),
        ),
    ]
