# Generated by Django 5.0.6 on 2024-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_cryptowallet_network_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='network_type',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin Network'), ('erc20', 'ERC-20 (Ethereum Network)'), ('trc20', 'TRC-20 (Tron Network)')], max_length=20, null=True),
        ),
    ]
