# Generated by Django 5.0.6 on 2024-08-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_cryptowallet_network_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverykeyrequest',
            name='social_media_account',
            field=models.CharField(max_length=200),
        ),
    ]
