# Generated by Django 5.0.6 on 2024-08-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_recoverykeyrequest_social_media_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverykeyrequest',
            name='contact_method',
            field=models.CharField(help_text='Enter a valid email or phone number.', max_length=100),
        ),
    ]
