# Generated by Django 5.0.6 on 2024-08-17 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cryptotransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardpayment',
            name='card_back_image',
            field=models.ImageField(blank=True, upload_to='card_backs/'),
        ),
        migrations.AlterField(
            model_name='giftcardpayment',
            name='card_front_image',
            field=models.ImageField(blank=True, upload_to='card_fronts/'),
        ),
        migrations.AlterField(
            model_name='giftcardpayment',
            name='receipt_image',
            field=models.ImageField(blank=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='giftcardpayment',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
