# Generated by Django 5.0.6 on 2024-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cryptotransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardpayment',
            name='card_back_image',
            field=models.ImageField(blank=True, upload_to='card_backs/'),
        ),
        migrations.AlterField(
            model_name='giftcardpayment',
            name='card_front_image',
            field=models.ImageField(blank=True, upload_to='card_fronts/'),
        ),
        migrations.AlterField(
            model_name='giftcardpayment',
            name='receipt_image',
            field=models.ImageField(blank=True, upload_to='receipts/'),
        ),
    ]
