# Generated by Django 5.0.6 on 2024-08-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_giftcardpayment_card_back_image_and_more'),
        ('accounts', '0022_portfolio_wallet_transaction'),
    ]

    operations = [
    ]
